### ISSUE TITLE
{Bonded Feature Req} compatiblity with basic weapons

### ISSUE THREAD

**Issue by NattoRiisa** [iamkaf/mod-issues#1]
**Related mod**
( main mod that's being asked for request )
Bonded 

( mods that i ask the compat req to)
Basic Weapons - https://modrinth.com/mod/basic-weapons

**Describe your feature request**
Would love some compatibility with basic weapons! their weapons would not count experience on weapons despite it,,, being a weapon

**Comment by iamkaf** [comment]
Aight, will do.

**Comment by iamkaf** [comment]
I've completed it. You can download it [here](https://modrinth.com/mod/bonded-basic-weapons-compat) or [here](https://curseforge.com/minecraft/mc-mods/bonded-basic-weapons-compat) once it passes review. You can also join the Discord and I'll ping once it's out.
