### ISSUE TITLE
[Bug]: Recipies don't unlock when you craft or use a data pack that unlocks it all to see what it is. (Not sure if it's a bug or not)

### ISSUE THREAD

**Issue by Lenancha** [iamkaf/mod-issues#10]
### Which mod are you filling this issue for?

Other

### What happened?

So I put the upgrades into the crafting grid and they did not unlock and using a data pack from vanilla tweaks doesn't seem to unlock them either

### Minecraft Version

1.21.1

### Which mod loader are you using?

Fabric

### Mod Loader Version

16.5

**Comment by Lenancha** [comment]
This was on 1.21.4 not 1.21.1

**Comment by iamkaf** [comment]
The upgrades and dyeing won't show up in the crafting book because of the way they're registered. The recipes still work but you won't find them in the recipe book. It's not something I can fix at the moment.

**Comment by Lenancha** [comment]
That's unfortunate but hopefully you can figure out how to fix that eventually.
