### ISSUE TITLE
[Bug]: game crash 

### ISSUE THREAD

**Issue by josh321-dev** [iamkaf/mod-issues#11]
### Which mod are you filling this issue for?

Mochila

### What happened?

any time i try to move a backpack that is gold or higher or even hover my mouse over it   game crashes 

### Minecraft Version

1.21.4

### Which mod loader are you using?

Fabric

### Mod Loader Version

16.5

**Comment by iamkaf** [comment]
Can you post the mods you're using or a crash log?

**Comment by josh321-dev** [comment]
![mods - File Explorer 2024-12-21 10_34_54 AM](https://github.com/user-attachments/assets/51942157-804c-4669-856b-29f282559ba7)


idk if that helps ill try to get a crash log

**Comment by josh321-dev** [comment]
![mods - File Explorer 2024-12-21 10_34_54 AM](https://github.com/user-attachments/assets/8b0c7ab8-5cc1-4548-9d1d-b5ef77040f55)


ill try to get a crash log

**Comment by josh321-dev** [comment]
so if i fill a gold back pack or higher tier and move it or hover over it games crashes  i added the log i got hope it helps

[latest.log](https://github.com/user-attachments/files/18219087/latest.log)

**Comment by iamkaf** [comment]
Do you have Feather's Shulker Tooltips option turned on? If so, turn that off and see if it helps.
The problem is that Feather treats the backpacks like shulkers but if it's has more slots than a shulker the code panics.
Nothing I can do ☹️ specially since Feather is closed source.

**Comment by josh321-dev** [comment]
ill try that and let you know

**Comment by josh321-dev** [comment]
yea that seemed to work thank you so much cant believe i didn't try that

**Comment by iamkaf** [comment]
Awesome!
