### ISSUE TITLE
[Bug]: Game won't start up (crash report tag '1')

### ISSUE THREAD

**Issue by Callibean72** [iamkaf/mod-issues#15]
### Which mod are you filling this issue for?

Amber, Liteminer

### What happened?

I installed Liteminer and was told that I also need Amber so I installed that, but when I go to start the game a crash report pops up. I had a similar issue with some totally unrelated mods but couldn't get it to work. 
![image_2024-12-30_153753249](https://github.com/user-attachments/assets/4d74e650-90a4-4398-a4d7-e6f5aceb3d9c)

### Minecraft Version

1.21.4

### Which mod loader are you using?

Fabric

### Mod Loader Version

0.16.9

### Mod List

```shell
Mods in folder (all mods are fabric and up to date and typed out more or less how it shows in my folder):
amber
appleskin
architectury
balm
cloth config
collective
cristellib
cubes-without-boarders
doubles doors
dynamic crosshair
fabric api
jade
jamlib
journey map
liteminer
REI
sodium
sound physics remastered
stack refill
supermartijnconfiglib
supermartijncorelib
tree harvester
waystones
youritemsaresafe
zume
```

**Comment by iamkaf** [comment]
Looks like you're missing [Forge Config API Port](https://modrinth.com/mod/forge-config-api-port), do you see it in the mods folder?

**Comment by Callibean72** [comment]
Thank you, with that it works now

**Comment by iamkaf** [comment]
Awesome! 😄
