### ISSUE TITLE
[Bug]: Amber Lib v1.2.1-beta.1 for NeoForge is marked as being for Fabric on CurseForge

### ISSUE THREAD

**Issue by unilock** [iamkaf/mod-issues#2]
### Which mod are you filling this issue for?

Amber

### What happened?

<img width="850" alt="image" src="https://github.com/user-attachments/assets/0d25324b-b2b4-4fbf-8365-0db50558220c">

### Minecraft Version

1.21.1

### Which mod loader are you using?

NeoForge

### Mod Loader Version

21.1.80

**Comment by iamkaf** [comment]
Good catch, thank you for letting me know!
I'm switching my publishing workflow from manual to automated today, this won't happen again.
