### ISSUE TITLE
[Bug]: can mine bedrock using any mining setting other than shapeless

### ISSUE THREAD

**Issue by Noku269** [iamkaf/mod-issues#3]
### Which mod are you filling this issue for?

Liteminer

### What happened?

if bedrock is highlighted in any mining selection it is also mined, if for example you mine a tunnel straight down with the small tunnel selection you will fall through the world and die

### Minecraft Version

1.21.1

### Which mod loader are you using?

Fabric

### Mod Loader Version

16.9

**Comment by iamkaf** [comment]
No wayyyyy. 😭 I'm going to fix it right away. I hope I didn't make any nasty void holes in your world. 🥲

**Comment by iamkaf** [comment]
Done! It's fixed on `0.3.1-beta.4`.
