### ISSUE TITLE
Make Netherite backpack cheaper

### ISSUE THREAD

**Issue by NiTiSon** [iamkaf/mod-issues#9]
**Related mod**
Mochila

**Describe your feature request**
Make Netherite Backpack upgradable like other Netherite items: 8 Netherite ingots are too expensive for single backpack

**Comment by iamkaf** [comment]
Yeah, I'll change it soon, I've been meaning too. Expect it in the next update.

**Comment by iamkaf** [comment]
I added a normal smithing recipe for the netherite upgrades. It's out now on version **1.3.1** for mc 1.21.1 and 1.21.4.
